name: Full Stack CI/CD

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend
      - name: Install Backend
        run: |
          cd server
          npm install
          npm run build

      - name: Test Backend
        run: |
          cd server
          npm test || echo "No tests"

      # Frontend
      - name: Install Frontend
        run: |
          cd client
          npm install

      - name: Lint Frontend
        run: |
          cd client
          npm run lint || echo "No lint"